export const SIGNUP = 'SIGNUP';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const AUTH_WITH_TOKEN = 'AUTH_WITH_TOKEN';
export const AUTH_WITH_TOKEN_REQUEST = 'AUTH_WITH_TOKEN_REQUEST';
export const AUTH_WITH_TOKEN_FAILURE = 'AUTH_WITH_TOKEN_FAILURE';

export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';
